name: to cache dependencies
description: cache dependencies to speed up workflow runs 
inputs:
  caching_enabled:
    description: 'Enable or disable caching of dependencies'
    required: false
    default: 'true'
outputs:
  caching_process:
    description: 'Indicates if the caching process was executed'
    value: ${{steps.install-deps.outputs.caching_process}}
runs:
  using: 'composite'
  steps:
    - name: Cache dependencies
      if: ${{ inputs.caching_enabled == 'true' }}
      uses: actions/cache@v3
      with:
        path: node_modules
        key: deps-node-modules-${{ hashFiles('**/package-lock.json') }}
    - name: Install dependencies
      if: steps.cache.outputs.cache-hit != 'true' || ${{ inputs.caching_enabled != 'true' }}
      id: install-deps
      shell: bash
      run: |
        npm ci
        echo "caching_process=true" >> $GITHUB_OUTPUT
      
